/**
 * Simple Log Analyzer API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const CompressionMode = {
    none: 'none',
    gzip: 'gzip'
} as const;
export type CompressionMode = typeof CompressionMode[keyof typeof CompressionMode];

