/**
 * Simple Log Analyzer API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LogFormat } from './logFormat';
import { CompressionMode } from './compressionMode';


export interface CreateLogGroupRequest { 
    name: string;
    format: LogFormat;
    description?: string | null;
    compression?: CompressionMode;
}
export namespace CreateLogGroupRequest {
}


