/**
 * Simple Log Analyzer API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ErrorCode } from './errorCode';


export interface ErrorResponse { 
    code: ErrorCode;
    message: string;
}
export namespace ErrorResponse {
}


