/**
 * Simple Log Analyzer API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const ErrorCode = {
    BAD_REQUEST: 'BAD_REQUEST',
    INVALID_NAME: 'INVALID_NAME',
    LOG_GROUP_ALREADY_EXISTS: 'LOG_GROUP_ALREADY_EXISTS',
    LOG_GROUP_NOT_FOUND: 'LOG_GROUP_NOT_FOUND',
    LOG_GROUP_NOT_EMPTY: 'LOG_GROUP_NOT_EMPTY',
    LOG_STREAM_ALREADY_EXISTS: 'LOG_STREAM_ALREADY_EXISTS',
    LOG_STREAM_NOT_FOUND: 'LOG_STREAM_NOT_FOUND',
    LOG_FILE_ALREADY_EXISTS: 'LOG_FILE_ALREADY_EXISTS',
    INTERNAL_FAILURE: 'INTERNAL_FAILURE'
} as const;
export type ErrorCode = typeof ErrorCode[keyof typeof ErrorCode];

