/**
 * Simple Log Analyzer API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LogFile { 
    logGroup: string;
    logStream: string;
    fileName: string;
    creationDate: string;
    lastModifiedDate: string;
    firstTimestamp: string;
    lastTimestamp: string;
}

