/**
 * Simple Log Analyzer API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const LogFormat = {
    plain_text: 'plain-text',
    json: 'json',
    logfmt: 'logfmt'
} as const;
export type LogFormat = typeof LogFormat[keyof typeof LogFormat];

