/**
 * Simple Log Analyzer API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LogFile } from './logFile';


export interface LogFilePage { 
    items: Array<LogFile>;
    nextPageToken?: string | null;
}

