/**
 * Simple Log Analyzer API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LogGroup } from './logGroup';


export interface LogGroupPage { 
    items: Array<LogGroup>;
    nextPageToken?: string | null;
}

