/**
 * Simple Log Analyzer API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LogStream } from './logStream';


export interface LogStreamPage { 
    items: Array<LogStream>;
    nextPageToken?: string | null;
}

