ktor {
    deployment {
        port = 8080
        port = ${?PORT}
    }
    application {
        modules = [ com.simpleloganalyzer.ingestion.ApplicationKt.module ]
    }
}

ingestion {
    dbPath = "data/ingestion.db"
    dbPath = ${?INGESTION_DB_PATH}
}
