/**
 * Simple Log Analyzer API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreateLogFileRequest } from '../model/models';
import { ErrorResponse } from '../model/models';
import { LogFile } from '../model/models';
import { LogFilePage } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface LogFilesServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Register a log file in a stream
     * 
     * @endpoint post /v1/log-groups/{group}/streams/{stream}/files
     * @param group 
     * @param stream 
     * @param createLogFileRequest 
     */
    createLogFile(group: string, stream: string, createLogFileRequest: CreateLogFileRequest, extraHttpRequestParams?: any): Observable<LogFile>;

    /**
     * List log files in a stream
     * 
     * @endpoint get /v1/log-groups/{group}/streams/{stream}/files
     * @param group 
     * @param stream 
     * @param pageSize 
     * @param pageToken 
     */
    listLogFiles(group: string, stream: string, pageSize?: number, pageToken?: string, extraHttpRequestParams?: any): Observable<LogFilePage>;

}
