/**
 * Simple Log Analyzer API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreateLogGroupRequest } from '../model/models';
import { ErrorResponse } from '../model/models';
import { LogGroup } from '../model/models';
import { LogGroupPage } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface LogGroupsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Create a log group
     * 
     * @endpoint post /v1/log-groups
     * @param createLogGroupRequest 
     */
    createLogGroup(createLogGroupRequest: CreateLogGroupRequest, extraHttpRequestParams?: any): Observable<LogGroup>;

    /**
     * Delete a log group
     * 
     * @endpoint delete /v1/log-groups/{name}
     * @param name 
     */
    deleteLogGroup(name: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Get a log group by name
     * 
     * @endpoint get /v1/log-groups/{name}
     * @param name 
     */
    getLogGroup(name: string, extraHttpRequestParams?: any): Observable<LogGroup>;

    /**
     * List log groups
     * 
     * @endpoint get /v1/log-groups
     * @param pageSize 
     * @param pageToken 
     */
    listLogGroups(pageSize?: number, pageToken?: string, extraHttpRequestParams?: any): Observable<LogGroupPage>;

}
