/**
 * Simple Log Analyzer API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreateLogStreamRequest } from '../model/models';
import { ErrorResponse } from '../model/models';
import { LogStream } from '../model/models';
import { LogStreamPage } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface LogStreamsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Create a log stream in a log group
     * 
     * @endpoint post /v1/log-groups/{group}/streams
     * @param group 
     * @param createLogStreamRequest 
     */
    createLogStream(group: string, createLogStreamRequest: CreateLogStreamRequest, extraHttpRequestParams?: any): Observable<LogStream>;

    /**
     * Delete a log stream and all its files
     * 
     * @endpoint delete /v1/log-groups/{group}/streams/{stream}
     * @param group 
     * @param stream 
     */
    deleteLogStream(group: string, stream: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * List log streams in a log group
     * 
     * @endpoint get /v1/log-groups/{group}/streams
     * @param group 
     * @param pageSize 
     * @param pageToken 
     */
    listLogStreams(group: string, pageSize?: number, pageToken?: string, extraHttpRequestParams?: any): Observable<LogStreamPage>;

}
